version: '3.7'

networks:
  symfony:

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - "8088:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - mysql
  #   networks:
  #     - symfony
  symfony5:
    image: 'docker.io/bitnami/symfony:1-debian-10'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
      - symfony

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb 
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - symfony

  # php:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./src:/var/www/html
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - symfony

  # composer:
  #   image: composer:latest
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   networks:
  #     - symfony

  # npm:
  #   image: node:latest
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   entrypoint: ['npm']
  #   networks:
  #     - symfony

  # artisan:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - mysql
  #   working_dir: /var/www/html
  #   entrypoint: ['/var/www/html/artisan']
  #   networks:
  #     - symfony

  phymyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - symfony

  dbbackup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./db-backup:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DB=mydb
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
    networks:
      - symfony