version: '3.7'

networks:
  wp-base:

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    depends_on: 
      - mysql
    ports:
      - 8282:80
    environment:
      #WORDPRESS_DB_HOST: mysql:5306
      WORDPRESS_DB_USER: mydbusername
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME:  mydb
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./src:/var/www/html
    networks:
      - wp-base

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydbusername
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wp-base

  wpcli:
    image: wordpress:cli
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - wp-base

 dbBackup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./db-backup:/backup
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DB=mydb
      - CRON_TIME=0 0 * * *
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - TIMEOUT=10s
      - INIT_BACKUP=1
    networks:
      - wp-base