version: '3.7'

networks:
  wp-elementor-test:

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8282:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./src:/var/www/html
    networks:
      - wp-elementor-test

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wp-elementor-test

  # wpcli:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: exampleuser
  #     WORDPRESS_DB_PASSWORD: examplepass
  #     WORDPRESS_DB_NAME: exampledb
  #   volumes:
  #     - ./src:/var/www/html
  #   working_dir: /var/www/html
  #   networks:
  #     - wp-elementor-test


  wpcli:
    image: wordpress:cli
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: exampleuser
    #   WORDPRESS_DB_PASSWORD: examplepass
    #   WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: 
      - /bin/sh -c "wp core update --path=/var/www/html"
      - /bin/sh -c "wp plugin install elementor --activate --path=/var/www/html"
      - /bin/sh -c "wp plugin install envato-elements --activate --path=/var/www/html"
      - /bin/sh -c "wp plugin install header-footer-elementor --activate --path=/var/www/html"
      - /bin/sh -c "wp theme install hello-elementor --activate --path=/var/www/html"
    networks:
      - wp-elementor-test