version: '3.7'

networks:
  wp-network:

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8380:80
    environment:
      #WORDPRESS_DB_HOST: mysql:8306
      WORDPRESS_DB_USER: mydbusername
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME:  mydb
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./src:/var/www/html
    networks:
      - wp-network

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydbusername
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "8306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wp-network

  wpcli:
    image: wordpress:cli
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8381:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - wp-network

  dbbackup:
    image: fradelg/mysql-cron-backup
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./db-backup:/backup
    environment:
      MYSQL_USER: root
      MYSQL_PASS: secret
      MYSQL_DB: mydb
      CRON_TIME: 0 0 * * *
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      TIMEOUT: 10s
      INIT_BACKUP: 1
    networks:
      - wp-network
